[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "av2"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]

dependencies = [
    "av",
    "click",
    "joblib",
    "kornia",
    "matplotlib",
    "nox",
    "numba",
    "numpy",
    "opencv-python",
    "pandas",
    "polars",
    "pyarrow",
    "pyproj",
    "rich",
    "scipy",
    "torch",
    "tqdm",
    "universal_pathlib",
]

dynamic = [
    "authors",
    "description",
    "license",
    "readme",
    "version"
]

[project.urls]
homepage = "argoverse.org"
repository = "https://github.com/argoverse/av2-api"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.isort]
known_first_party = "av2"
known_third_party = ""

line_length = 120
multi_line_output = 3
profile = "black"

[tool.mypy]
exclude = "build"
ignore_missing_imports = true
disallow_untyped_decorators = false
plugins = "numpy.typing.mypy_plugin"
strict = true

[tool.pylint]
max-line-length = 120

[tool.pyright]
include = ["src"]

reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUntypedFunctionDecorator = false

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov-report term-missing:skip-covered --cov av2"
testpaths = ["tests"]
