[package]
name = "av2"
version = "0.3.0"
edition = "2021"

[package.metadata.maturin]
name = "av2._r"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "av2"
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
glob = "0.3.1"
itertools = "0.10.5"
ndarray = { version = "0.15.6", features = [
    "matrixmultiply-threading",
    "rayon",
] }
numpy = { version = "0.18.0" }
once_cell = "1.17.1"
polars = { version = "0.27.2", features = [
    "dtype-u8",
    "lazy",
    "ndarray",
    "parquet",
    "ipc",
    "serde",
] }
pyo3 = { version = "0.18.1", features = ["extension-module"] }
pyo3-polars = { git = "https://github.com/benjaminrwilson/pyo3-polars" }
rayon = "1.6.1"
serde = "1.0.155"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
